# Generated by Django 6.0.1 on 2026-02-25 09:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('theme_preference', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('sepia', 'Сепия'), ('ocean', 'Океан'), ('forest', 'Лес')], default='light', max_length=20, verbose_name='Тема оформления')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('auto_save_interval', models.IntegerField(default=1, verbose_name='Интервал автосохранения (сек)')),
                ('total_notes', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
