# Generated by Django 6.0.1 on 2026-02-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='Заметка', max_length=50),
        ),
    ]
