# Generated by Django 6.0.1 on 2026-02-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_options_notes_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='notes',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
    ]
