# Generated by Django 6.0.1 on 2026-02-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_deleted_at_notes_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Изображения'),
        ),
    ]
