# Generated by Django 6.0.1 on 2026-03-02 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notes_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('color', models.CharField(default='indigo', max_length=20, verbose_name='Цвет группы')),
                ('icon', models.CharField(default='Folder', max_length=50, verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группа заметок',
                'verbose_name_plural': 'Группы заметок',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.AddField(
            model_name='notes',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.notegroup', verbose_name='Группа'),
        ),
    ]
