# Generated by Django 6.0.1 on 2026-04-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notegroup_notes_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(default='neutral', max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(default='neutral', max_length=50)),
                ('emotions', models.JSONField(default=dict)),
                ('keywords', models.JSONField(default=list)),
                ('entities', models.JSONField(default=dict)),
                ('topics', models.JSONField(default=list)),
                ('text_stats', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='notes.notes')),
            ],
            options={
                'verbose_name': 'Анализ заметки',
            },
        ),
    ]
