# Generated by Django 6.0.1 on 2026-04-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_noteanalysis_narrative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteanalysis',
            name='narrative',
        ),
    ]
