# Generated by Django 6.0.1 on 2026-04-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_remove_noteanalysis_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteanalysis',
            name='narrative',
            field=models.TextField(blank=True, default='', help_text='Текстовое описание заметки, сгенерированное локально', verbose_name='Нарратив'),
        ),
    ]
